apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  secret-key-base: MGQ5ODYyMjY3ZWUxNmZjMjE5NjkyMmExMDRhY2VlZWNiMmU3OTg0OWVjOTBiNWMxZWNiNzhkNTlhOTdmYmI0MTg4YmExYmU3MjViMThkN2RlMzIwNDdkNGMzOGUxZDRkOTkxN2FjZmE1MWIyMTViYTg5Mjc2MmEzZDM3NjI4M2U=